image: node:14.20.1

stages:
- build
- test
- deploy

test:
  stage: test
  script:
    - yarn
    - yarn test-coverage
  cache:
    paths:
    - node_modules
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
      junit: junit.xml

lint:
  stage: test
  allow_failure: true
  script:
    - yarn
    - yarn lint & yarn lint-junit
  cache:
    paths:
    - node_modules
  artifacts:
    reports:
      junit: junit.xml

build:
  stage: build
  script:
    - yarn
    - yarn build
  cache:
    paths:
    - node_modules
  artifacts:
    expire_in: 1 week
    paths:
      - build

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  script:
    - mv build public
  artifacts:
    expire_in: 1 week
    paths:
      - public
  needs:
    - job: build
      artifacts: true
  only:
    - main
